services:
  - type: web
    name: my-node-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
